import React, { Component } from 'react';
import {Link} from "react-router-dom";
class termsandconditions extends Component {
  render() {
    return (
      <div className="headerfix">
        <header id="page-header">
          <div className="container">
            <div className="row">
              <div className="col-md-6 m-auto text-center">
              <h1 className="text-white">Terms and Conditions </h1>
                
              </div>
            </div>
          </div>
        </header>
        <div className="card p-4">
                  <div className="card-body">
        <Link to="/" className="btn btn-light">
                  Go Back
                </Link>
       
      <h3 className="">Jagtu Farms Private Limited [JFPL]. </h3>

<p>Jagtu Farms Private Limited is just an information/service provider based on farmers/buyers’ inputs.  </p>
<p>Farmers/sellers/consumers/buyers are agreeing to comply latest amended <span style={{"font-Size": "18px", "color":"blue"}}>Essential Commodities Act 1955 and The Farming Produce Trade and Commerce (Promotion and Facilitation) Ordinance, 2020</span> at all times. 
</p>
<br/> 
<p>Farmers/seller and buyer are agreeing to pay service charges as applied to service provider (JAGTU FARMS PRIVATE LIMITED) </p>
<p>Farmers / sellers/ buyers are agreeing and accepting that Jagtu Farms Private Limited has authority to take any step/ action to sell/purchase grain/product on their behalf at any price without giving them prior notice. We are not responsible for their loss or profit.  We are just the managers/agents and service providers appointed by them (farmers/sellers/buyers/consumers).  </p>


<p>Farmers are responsible for transporting their goods / grains /products to buyers. Jagtu Farms Private Limited will be assisting them in selecting transportation means if required. </p>

<p>Any loss/damage/contamination of grain, Jagtu Farms Private Limited is not responsible. </p>

  

<h6>Conditions of Use</h6> 

<p>Welcome to Jagtu Farms Private Limited and its affiliates provide access to the<Link to="http://www.jagtu.com/home.html" target="_blank" rel="noopener noreferrer"> www.jagtu.com</Link> website (the "website") to you subject to the conditions set out on this page. </p>

<h6>Conditions of Sale  </h6>

<p>Please read these conditions carefully before using the<a href="http://www.jagtu.com/home.html" target="_blank" rel="noopener noreferrer"> www.jagtu.com</a> website. By using the<a href="http://www.jagtu.com/home.html" target="_blank" rel="noopener noreferrer"> www.Jagtu.com</a> website, you signify your agreement to be bound by these conditions. </p>

<p>In addition, when you use any current or future<a href="http://www.jagtu.com/home.html" target="_blank" rel="noopener noreferrer"> www.Jagtu.com</a> service (like Wish List or Marketplace) ("Jagtu Farms Private Limited "), you will also be subject to the terms, guidelines and conditions applicable to that Jagtu Farms Private Limited. ("Terms"). If these Conditions of Use are inconsistent with such Terms, the Terms will control. </p>

<p>These "Conditions of Use" constitute an electronic record within the meaning of the applicable law. This electronic record is generated by a computer system and does not require any physical or digital signatures. </p>

 

<h5>Conditions Relating to Your Use of www.Jagtu.com</h5> 

<h6>1. Your Account </h6>

 

<p>If you use the website, you are responsible for maintaining the confidentiality of your account and password and for restricting access to your computer to prevent unauthorised access to your account. You agree to accept responsibility for all activities that occur under your account or password. You should take all necessary steps to ensure that the password is kept confidential and secure and should inform us immediately if you have any reason to believe that your password has become known to anyone else, or if the password is being, or is likely to be, used in an unauthorised manner. Please ensure that the details you provide us with are correct and complete and inform us immediately of any changes to the information that you provided when registering. You can access and update much of the information you provided us with in the Your Account area of the website. You agree and acknowledge that you will use your account on the website to purchase/ sell products only for your personal /corporate use and not for business purposes. business only can be done after changing shape/ physical appearance of raw materials. <a href="http://www.jagtu.com/home.html" target="_blank" rel="noopener noreferrer"> www.Jagtu.com</a> reserves the right to refuse access to the website, terminate accounts, remove or edit content at any time without notice to you. </p>

 

<h6>2. Privacy</h6> 

 

<p>Please review our Privacy Notice, which also governs your visit to Jagtu.com, to understand our practices. The personal information / data provided to us by you during the course of usage of Jagtu.com will be treated as strictly confidential and in accordance with the Privacy Notice and applicable laws and regulations. If you object to your information being transferred or used, please do not use the website. </p>

 

<h6>3. E-Platform for Communication </h6>

 

<p>You agree, understand and acknowledge that the website is an online platform that enables you to purchase/ sell products listed on the website at the price indicated therein at any time from any location. You further agree and acknowledge that Jagtu Farms Private Limited is only a facilitator and is not and cannot be a party to or control in any manner any transactions on the website. Accordingly, the contract of sale of products on the website shall be a strictly bipartite contract between purchaser and the farmer/sellers on <a href="http://www.jagtu.com/home.html" target="_blank" rel="noopener noreferrer">jagtu.com</a> </p>

 

 

<h6>4. Access to <a href="http://www.jagtu.com/home.html" target="_blank" rel="noopener noreferrer">jagtu.com </a></h6>

 

<p>We will do our utmost to ensure that availability of the website will be uninterrupted and that transmissions will be error-free. However, due to the nature of the Internet, this cannot be guaranteed. Also, your access to the website may also be occasionally suspended or restricted to allow for repairs, maintenance, or the introduction of new facilities or services at any time without prior notice. We will attempt to limit the frequency and duration of any such suspension or restriction. </p>

 

<h6>5. Licence for website access </h6>

 

<p>Subject to your compliance with these Conditions of Use and payment of applicable fees, if any, Jagtu Farms  Private Limited grants you a limited licence to access and make personal use of this website, but not to download (other than page caching) or modify it, or any portion of it, except with express written consent of Jagtu Farms  Private Limited and / or its affiliates, as may be applicable. This licence does not include any resale or commercial use of this website or its contents; any collection and use of any product listings, descriptions, or prices; any derivative use of this website or its contents; any downloading or copying of account information for the benefit of another seller/purchaser ; or any use of data mining, robots, or similar data gathering and extraction tools. </p>

 

<p>This website or any portion of this website (including but not limited to any copyrighted material, trademarks, or other proprietary information) may not be reproduced, duplicated, copied, sold, resold, visited, distributed or otherwise exploited for any commercial purpose without express written consent of Jagtu Farms Private Limited and / or its affiliates, as may be applicable. </p>

 

<p>You may not frame or use framing techniques to enclose any trademark, logo, or other proprietary information (including images, text, page layout, or form) of www.jagtu.com and its affiliates without express written consent. You may not use any meta tags or any other "hidden text" utilising Jagtu Farms Private Limited' s or its affiliates' names or trademarks without the express written consent of jagtu Farms Private Limited and / or its affiliates, as applicable. Any unauthorised use terminates the permission or license granted by Jagtu Farms Private Limited and / or its affiliates, as applicable. </p>

 

<p>You are granted a limited, revocable, and non-exclusive right to create a hyperlink to the Welcome page of www.jagtu.com as long as the link does not portray Jagtu Farms Private Limited, www.jagtu.com, their affiliates, or their products or services in a false, misleading, derogatory, or otherwise offensive matter. You may not use any www.jagtu.com logo or other proprietary graphic or trademark as part of the link without express written consent of Jagtu Farms Private Limited and / or its affiliates, as may be applicable. </p>
 

 

<h6>6. Your Conduct</h6> 

 

<p>You must not use the website in any way that causes, or is likely to cause, the website or access to it to be interrupted, damaged or impaired in any way You understand that you, and not www.jagtu.com,  are responsible for all electronic communications and content sent from your computer to us and you must use the website for lawful purposes only. You must not use the website for any of the following: </p>

<p>for fraudulent purposes, or in connection with a criminal offense or other unlawful activity </p>

<p>to send, use or reuse any material that does not belong to you; or is illegal, offensive (including but not limited to material that is sexually explicit content or which promotes racism, bigotry, hatred or physical harm), deceptive, misleading, abusive, indecent, harassing, blasphemous, defamatory, libellous, obscene, pornographic, podophilic or menacing; ethnically objectionable, disparaging or in breach of copyright, trademark, confidentiality, privacy or any other proprietary information or right; or is otherwise injurious to third parties; or relates to or promotes money laundering or gambling; or is harmful to minors in any way; or impersonates another person; or threatens the unity, integrity, security or sovereignty of India or friendly relations with foreign States; or objectionable or otherwise unlawful in any manner whatsoever; or which consists of or contains software viruses, political campaigning, commercial solicitation, chain letters, mass mailings or any "spam </p>

<p>to cause annoyance, inconvenience or needless anxiety </p>

<h6>7. Reviews, comments, communications and other content </h6>

 

<p>Users of this website may post reviews, comments and other content; send communications; and submit suggestions, ideas, comments, questions, or other information, as long as the content is not illegal, obscene, abusive, threatening, defamatory, invasive of privacy, infringing of intellectual property rights, or otherwise injurious to third parties, or objectionable and does not consist of or contain software viruses, political campaigning, commercial solicitation, chain letters, mass mailings, or any form of "spam." In the event a user uses a false e-mail address, impersonates any person or entity, or otherwise misleads as to the origin of any content. www.jagtu.com reserves the right (but not the obligation) to remove, refuse, delete or edit any content that in the sole judgement of www.jagtu.com violates these Conditions of use and, or terminate your permission to access or use this website. </p>

 

<p>If you do post content or submit material, and unless we indicate otherwise, you </p>

<p>(a) grant Jagtu Farms Private Limited and its affiliates a non-exclusive, royalty-free, irrevocable, perpetual and fully sublicensable rights to use, reproduce, modify, adapt, publish, translate, create derivative works from, distribute, and display such content throughout the world in any media; and </p>

<p>(b) Jagtu Limited  Private Limited and its affiliates and sublicensees the right to use the name that you submit in connection with such content, if they choose. </p>

<p>You agree that the rights you grant above are irrevocable during the entire period of protection of your intellectual property rights associated with such content and material. You agree to waive your right to be identified as the author of such content and your right to object to derogatory treatment of such content. You agree to perform all further acts necessary to perfect any of the above rights granted by you to Jagtu Farms Private Limited, including the execution of deeds and documents, at its request. </p>

 

<p>You represent and warrant that you own or otherwise control all of the rights to the content that you post or that you otherwise provide on or through the website; that, as at the date that the content or material is submitted to <a href="http://www.jagtu.com/home.html" target="_blank" rel="noopener noreferrer">www.jagtu.com</a> </p>

         <p>  (i) the content and material are accurate; </p>

         <p> (ii) use of the content and material you supply does not breach any applicable www.jagtu.com policies or guidelines and will not cause injury to any person or entity (including that the content or material is not defamatory); </p>

         <p> (iii) the content is lawful. You agree to indemnify Jagtu Farms  Private Limited and its affiliates for all claims brought by a third party against it or its affiliates arising out of or in connection with a breach of any of these warranties. </p>

 

<h6>8. Claims against Objectionable Content </h6>

 

<p>Because <a href="http://www.jagtu.com/home.html" target="_blank" rel="noopener noreferrer">www.jagtu.com</a> lists millions of products for sale offered by sellers on the website and hosts many thousands of comments, it is not possible for us to be aware of the contents of each product listed for sale, or each comment or review that is displayed. Accordingly, www.jagtu.com operates on a "notice and takedown" basis. If you believe that any content on the website is illegal, offensive (including but not limited to material that is sexually explicit content or which promotes racism, bigotry, hatred or physical harm), deceptive, misleading, abusive, indecent, harassing, blasphemous, defamatory, libellous, obscene, pornographic, podophilic or menacing; ethnically objectionable, disparaging; or is otherwise injurious to third parties; or relates to or promotes money laundering or gambling; or is harmful to minors in any way; or impersonates another person; or threatens the unity, integrity, security or sovereignty of India or friendly relations with foreign States; or objectionable or otherwise unlawful in any manner whatsoever; or which consists of or contains software viruses, (" Objectionable Content "), please notify us immediately by following our Notice and Procedure for Making Claims of Right Infringements. Once this procedure has been followed, www.jagtu.com will make all reasonable endeavours to remove such Objectionable Content complained about within a reasonable time. </p>

 

<h6>9. Copyright, authors' rights and database rights </h6>

 

<p>All content included on the website, such as text, graphics, logos, button icons, images, audio clips, digital downloads, data compilations, and software, is the property of Jagtu Farms Private Limited, its affiliates or its content suppliers and is protected by India copyright, authors' rights and database right laws. The compilation of all content on this website is the exclusive property of Jagtu Farms Private Limited and its affiliates and is protected by laws of India copyright and database right laws. All software used on this website is the property of Jagtu Farms Private Limited, its affiliates or its software suppliers and is protected by India copyright and author' rights laws. </p>

 

<p>You may not systematically extract/ or re-utilise parts of the contents of the website without Jagtu Farms Private Limited and / or its affiliates (as may be applicable) express written consent. In particular, you may not utilise any data mining, robots, or similar data gathering and extraction tools to extract (whether once or many times) for re-utilisation of any substantial parts of this website, without Jagtu Farms Private Limited and / or its affiliates (as may be applicable) express written consent. You may also not create and/ or publish your own database that features substantial (eg: prices and product listings) parts of this website without Jagtu Farms Private Limited and / or its affiliates (as may be applicable) express written consent. </p>

 

<h6>10. Intellectual Property Claims</h6> 

 

<p>Jagtu Farms Private Limited and its affiliates respect the intellectual property of others. If you believe that your intellectual property rights have been used in a way that gives rise to concerns of infringement, please follow our Notice and Procedure for Making Claims of Right Infringements. </p>

 

<h6>11. Trademarks </h6>

 

<a href="http://www.jagtu.com/home.html" target="_blank" rel="noopener noreferrer">www.jagtu.com</a>, Jagtu Farms  Private Limited , Jagtu Farms  Private Limited  LOGO, PAYPAGE and other marks indicated on our website are trademarks or registered trademarks of <a href="http://www.jagtu.com/home.html" target="_blank" rel="noopener noreferrer">www.jagtu.com</a>, or its subsidiaries (collectively "Jagtu Farms  Private Limited "), in jurisdictions. www.jagtu.com's graphics, logos, page headers, button icons, scripts and service names are the trademarks or trade dress of Jagtu Farms Private Limited. Jagtu Farms Private Limited 's trademarks and trade dress may not be used in connection with any product or service that is not Jagtu Farms Private Limited 's, in any manner that is likely to cause confusion among customers, or in any manner that disparages or discredits Jagtu Farms Private Limited. All other trademarks not owned by Jagtu Farms Private Limited that appear on this website are the property of their respective owners, who may or may not be affiliated with, connected to, or sponsored by Jagtu Farms Private Limited. 

 

<h6>13. Disclaimer </h6>

 

<p>You acknowledge and undertake that you are accessing the services on the website and transacting at your own risk and are using your best and prudent judgment before entering into any transactions through the website. You further acknowledge and undertake that you will use the website to order products only for your personal use and not for business purposes. We shall neither be liable nor responsible for any actions or inactions of sellers nor any breach of conditions, representations or warranties by the sellers or manufacturers of the products and hereby expressly disclaim and any all responsibility and liability in that regard. We shall not mediate or resolve any dispute or disagreement between you and the sellers or manufacturers of the products. </p>

 

<p>We further expressly disclaim any warranties or representations (express or implied) in respect of quality, suitability, accuracy, reliability, completeness, timeliness, performance, safety, merchantability, fitness for a particular purpose, or legality of the products listed or displayed or transacted or the content (including product or pricing information and/or specifications) on the website. While we have taken precautions to avoid inaccuracies in content, this website, all content, information (including the price of products), software, products, services and related graphics are provided as is, without warranty of any kind. We do not implicitly or explicitly support or endorse the sale or purchase of any products on the website. At no time shall any right, title or interest in the products sold through or displayed on the website vest with Jagtu Farms Private Limited nor shall www.jagtu.com have any obligations or liabilities in respect of any transactions on the website.</p>

 

<h6>14. Indemnity and Release </h6>

 

<p>You shall indemnify and hold harmless Jagtu Private Limited, its subsidiaries, affiliates and their respective officers, directors, agents and employees, from any claim or demand, or actions including reasonable attorney's fees, made by any third party or penalty imposed due to or arising out of your breach of these Conditions of Use or any document incorporated by reference, or your violation of any law, rules, regulations or the rights of a third party. </p>

 

<p>You hereby expressly release Jagtu Farms Private Limited and/or its affiliates and/or any of its officers and representatives from any cost, damage, liability or other consequence of any of the actions/inactions of the vendors and specifically waiver any claims or demands that you may have in this behalf under any statute, contract or otherwise. </p>

 

<h6>15. Children</h6> 
 

<p>Use of <a href="http://www.jagtu.com/home.html" target="_blank" rel="noopener noreferrer">www.jagtu.com</a> is available only to persons who can form a legally binding contract under the Indian Contract Act, 1872. If you are a minor i.e. under the age of 18 years, you may use <a href="http://www.jagtu.com/home.html" target="_blank" rel="noopener noreferrer">www.jagtu.com</a> only with the involvement of a parent or guardian. </p>

 

<h6>16. Other Businesses </h6>

 

<p>Parties other than Jagtu Farms Private Limited and its affiliates may operate stores, provide services, or sell product lines on www.jagtu.com. For example, businesses and individuals offer products via Marketplace. In addition, we provide links to the websites of affiliated companies and certain other businesses. We are not responsible for examining or evaluating, and we do not warrant or endorse the offerings of any of these businesses or individuals, or the content of their websites. Jagtu Farms Private Limited does not assume any responsibility or liability for the actions, products, and content of any of these and any other third-parties. You can tell when a third-party is involved in your transactions, and we may share customer information related to those transactions with that third-party. You should carefully review their privacy statements and other conditions of use. </p>

 

<h6>17. Communications </h6>

 

<p>When you visit www.jagtu.com, you are communicating with us electronically. You will be required to provide a valid phone number and/or area pin code while placing an order with us. We may communicate with you by e-mail, SMS, phone call or by posting notices on the website or by any other mode of communication. For contractual purposes, you consent to receive communications (including transactional, promotional and/or commercial messages), from us with respect to your use of the website and/or your order placed on the website. </p>

<h6>18. Losses </h6>

 

<p>We will not be responsible for any business loss (including loss of profits, revenue, contracts, anticipated savings, data, goodwill or wasted expenditure) or any other indirect or consequential loss that is not reasonably foreseeable to both you and us when you commenced using the website. </p>

 

<h6>19. Alteration of Service or Amendments to the Conditions </h6>

 

<p>We reserve the right to make changes to our website, policies, and these Conditions of Use at any time. You will be subject to the policies and Conditions of Use in force at the time that you use the website or that you order goods from us, unless any change to those policies or these conditions is required to be made by law or government authority (in which case it will apply to orders previously placed by you). If any of these conditions is deemed invalid, void, or for any reason unenforceable, that condition will be deemed severable and will not affect the validity and enforceability of any remaining condition. </p>

 

<h6>20. Events beyond our reasonable control </h6>

 

<p>We will not be held responsible for any delay or failure to comply with our obligations under these conditions if the delay or failure arises from any cause which is beyond our reasonable control. This condition does not affect your statutory rights. </p>

 

<h6>21. Waiver </h6>

 

<p>If you breach these conditions and we take no action, we will still be entitled to use our rights and remedies in any other situation where you breach these conditions.</p> 

 

<h6>22. Governing law and Jurisdiction </h6>

 

<p>These conditions are governed by and construed in accordance with the laws of India. You agree, as we do, to submit to the exclusive jurisdiction of the courts at Lucknow. </p>

 

<h6>23. Our Details</h6>

 

<p>This website is operated by Jagtu Farms Private Limited. </p>

 

<p>For the <a  href="http://www.jagtu.com/home.html" target="_blank" rel="noopener noreferrer"> www.jagtu.com</a> website, you could contact us by visiting: </p>

<a href="www.jagtu.com/contact-us">www.jagtu.com/contact-us </a> 

<h6>24. Jagtu Farms Private Limited Software Terms </h6>

 

<p>In addition to these Conditions of Use, the terms found here apply to any software (including any updates or upgrades to the software and any related documentation) that we make available to you from time to time for your use in connection with Jagtu Farms  Private Limited (the "Jagtu Farms  Private Limited  Software"). </p>

 

<p>Notice and Procedure for Making Claims of Right Infringements</p> 

<p>If you believe that your rights are being infringed, you may fill out and submit the Notice Form. We respond expeditiously to rights owners and their agents who complete and submit the Notice Form to communicate concerns about any alleged infringement. </p>

 

<p>Upon receipt of a Notice Form we may take certain actions, including removing information or an item, all of which are taken without any admission as to liability and without prejudice to any rights, remedies or defenses, all of which are expressly reserved. Furthermore, in submitting a Notice Form, you grant to Jagtu Farms Private Limited the right to use, reproduce, modify, adapt, publish, translate, create derivative works from, and display its content throughout the world in any media. This includes forwarding the Notice Form to the parties involved in the provision of the allegedly infringing content. You agree to indemnify Jagtu Farms Private Limited for all claims brought by a third party against Jagtu Farms Private Limited arising out of or in connection with the submission of a Notice Form. </p>

 

<p>Note on Third Party Seller Listings: Please keep in mind that Third Party Seller listings are merely hosted on www.jagtu.com and are posted solely at the direction of Third Party Sellers who may be contacted via their "Seller Information" page, accessible from any of their listings. </p>

 

<p>Important Warning: giving false, misleading or inaccurate information in the Notice Form to Jagtu Farms Private Limited may result in civil and/or criminal liability. You should contact a legal advisor should you have any questions. </p>

 

<h6>Notice Form: </h6>

 

<p>If you believe that your rights are being violated by an item or information on the <a href="http://www.jagtu.com/home.html" target="_blank" rel="noopener noreferrer">www.jagtu.com</a> site, you may fill out and submit the Notice Form (below). This signed form can be sent via E-mail PDF or Fax to the Grievance Officer:</p> 

 

<p>Name: Ankit Kumar</p> 

<p>e-mail PDF: info@jagtu.com</p> 

<p>(We will accept a signed PDF via e-mail with the subject line "Claim of Infringement" unless by prior agreement we have agreed with you for an alternative receipt mechanism, if any).  </p>

<p>Please note that this procedure is exclusively for notifying<a href="http://www.jagtu.com/home.html" target="_blank" rel="noopener noreferrer"> www.jagtu.com</a> of Objectionable Content on or advertised for sale on the<a href="http://www.jagtu.com/home.html" target="_blank" rel="noopener noreferrer"> www.jagtu.com</a> website. Please provide your address, telephone number, and e-mail address when sending the notice to us. </p>

 

<p>Important Warning: Giving false, misleading or inaccurate information in the Notice to<a href="http://www.jagtu.com/home.html" target="_blank" rel="noopener noreferrer"> www.jagtu.com</a> may result in civil and/ or criminal liability. </p>

 

 

<p>Notice to<a href="http://www.jagtu.com/home.html" target="_blank" rel="noopener noreferrer"> www.jagtu.com</a> of Objectionable Content. </p>

 

<p>In the matter of<a href="http://www.jagtu.com/home.html" target="_blank" rel="noopener noreferrer"> www.jagtu.com</a> </p>

 

<p>I, [Please set out your full name] of [please give your postal address], [please set your occupation], says as follows: </p>

 

 

<p>I refer to the website<a href="http://www.jagtu.com/home.html" target="_blank" rel="noopener noreferrer"> www.jagtu.com</a> ("the website"). I make this statement in support of my giving jagtu.com notice that, via the website, it is causing or contributing to the publication of Objectionable Content. </p>

<p>The Objectionable Content (delete whichever paragraph is not applicable):  </p>

<p>(a) appear in a book being sold by jagtu.com via the website entitled [please state the book name and its author]. The Objectionable Content appear on page [please state the page number(s) where you consider the words constitute Objectionable Content]. </p>

<p>OR (b) appear on the website at [please cut and paste the address of the relevant Web page from the website where the Objectionable Content appears]. </p>

<p>The words/ content that I consider to be Objectionable Content are [please repeat the exact words you are complaining about]. </p>

<p>This content is Objectionable Content because [please state why you consider the content is Objectionable Content]. </p>

<p>I understand that this statement may be used in any court proceedings that may arise out of or relating to the Objectionable Content which I have complained about. </p>

<h6>Statement of Truth </h6>

 

<p>I declare the facts stated above to be true. </p>

 

<h6>Signed: </h6> 

 

<h6>Dated: </h6>

 

<p>Please read the conditions of use carefully before using the jagtu.com website. By using the jagtu.com website, you signify your agreement to be bound by these conditions. </p>

 

 

<h5>Jagtu Farms Private Limited Software Terms</h5> 

<p>1. Use of the Jagtu Farms Private Limited Software </p>

 

<p>You may use Jagtu Farms Private Limited Software solely for purposes of enabling you to use and enjoy the Jagtu Farms Private Limited Services as provided by Jagtu Farms Private Limited, and as permitted by the Conditions of Use, these Jagtu Farms Private Limited Software Terms and any Terms. You may not incorporate any portion of the Jagtu Farms  Private Limited  Software into your own programs or compile any portion of it in combination with your own programs, transfer it for use with another service, or sell, rent, lease, lend, loan, distribute or sub-license the Jagtu Farms  Private Limited  Software or otherwise assign any rights to the Jagtu Farms  Private Limited  Software in whole or in part. You may not use the Jagtu Farms Private Limited Software for any illegal purpose. We may cease providing any Jagtu Farms Private Limited Software and we may terminate your right to use any Jagtu Farms Private Limited Software at any time. Your rights to use the Jagtu Farms Private Limited Software will automatically terminate without notice from us if you fail to comply with any of these Jagtu Farms Private Limited Software Terms, the Conditions of Use or any other Terms. Additional third-party terms contained within or distributed with certain Jagtu Farms Private Limited Software that are specifically identified in related documentation may apply to that Jagtu Farms Private Limited Software (or software incorporated with the Jagtu Farms Private Limited Software) and will govern the use of such software in the event of a conflict with these Conditions of Use. All software used in any Jagtu Farms Private Limited Service is the property of Jagtu Farms Private Limited and/or its affiliates or its software suppliers and protected by laws of India including but not limited to any other applicable copyright laws. </p>

 

<h6>2. Use of Third-Party Services </h6>

 

<p>When you use the Jagtu Farms Private Limited Software, you may also be using the services of one or more third parties, such as a wireless carrier or a mobile platform provider. Your use of these third-party services may be subject to the separate policies, terms of use, and fees of these third parties. </p>

 


<h6>3. No Reverse Engineering </h6>

 


<p>You may not, and you will not encourage, assist or authorize any other person to copy, modify, reverse engineer, decompile or disassemble, or otherwise tamper with, the Jagtu Farms Private Limited Software, whether in whole or in part, or create any derivative works from or of the Jagtu Farms Private Limited Software. </p>

 


<h6>Updates </h6>

 


<p>In order to keep the Jagtu Farms Private Limited Software up-to-date, we may offer automatic or manual updates at any time and without notice to you. </p>

 


<p>Conditions of Sale (between Farmers/Sellers and the Customer/buyer) </p>


<p>Please read these conditions carefully before placing an order for any products with the Sellers ("We" or "Our" or "Us", wherever applicable) on the<a href="http://www.jagtu.com/home.html" target="_blank" rel="noopener noreferrer"> www.jagtu.com</a> (the website). These conditions signify your agreement to be bound by these conditions. </p>

 


<p>In addition, when you use any current or future<a href="http://www.jagtu.com/home.html" target="_blank" rel="noopener noreferrer"> www.jagtu.com</a> service, you will also be subject to the terms, guidelines and conditions applicable to that service ("Terms"). If these Conditions of Sale are inconsistent with such Terms, the Terms will control. </p>

 


<h6>1. Conditions Relating to the Sale of Products to You </h6>

 


<p>This section deals with conditions relating to the sale of products on the website by us to you. </p>

 


<h6>2. Our Contract </h6>

 


<p>Your order is an offer to us to buy the product(s) in your order. When you place an order to purchase a product from us, you will receive an e-mail confirming receipt of your order and containing the details of your order (the "Order Confirmation E-mail"). The Order Confirmation E-mail is acknowledgement that we have received your order, and does not confirm acceptance of your offer to buy the product(s) ordered. We only accept your offer, and conclude the contract of sale for a product ordered by you, when the product is dispatched to you and an e-mail confirmation is sent to you that the product has been dispatched to you (the "Dispatch Confirmation E-mail"). If your order is dispatched in more than one package, you may receive a separate Dispatch Confirmation E-mail for each package, and each Dispatch Confirmation E-mail and corresponding 
  dispatch will conclude a separate contract of sale between you and us for the product(s) specified in that Dispatch Confirmation E-mail.</p> 

 


<p>Your contract is with us (the Farmers) and you confirm that the product(s) ordered by you are purchased for your internal / personal purpose and not for re-sale or business purpose. You authorize us to declare and provide declaration to any governmental authority on your behalf stating the aforesaid purpose of the products ordered by you on the website. </p>

 


<p>You can cancel your order for a product at no cost any time before we send the Dispatch Confirmation E-mail relating to that product. </p>

 


<h6>3. Returns </h6>

 


<p>Please review our Returns Policy, which applies to products sold by us. </p>

 


<h6>4. Pricing and availability </h6>

 

<p>We list availability information for products sold by us on behalf of farmers on the website, including on each product information page. Beyond what we say on that page or otherwise on the website, we cannot be more specific about availability. Please note that dispatch estimates are just that. They are not guaranteed dispatch times and should not be relied upon as such. As we process your order, you will be informed by e-mail if any products you order turn out to be unavailable.</p> 

 

<p>For more details, please review our Pricing policy and our Availability Guide, both of which apply to products ordered from us. </p>

 

<p>All prices are inclusive of VAT/CST, service tax, Goods and Services Tax ("GST"), duties and cesses as applicable - unless stated otherwise.</p> 

 

<h6>5. Taxes </h6>

 

<p>You shall be responsible for payment of all fees/costs/charges associated with the purchase of products from us and you agree to bear any and all applicable taxes including but not limited to VAT/CST, service tax, GST, duties and cesses etc.  (if applicable) </p>

 

<h6>6. Health & Safety </h6>

 

<p>By purchasing any product from our Home/ website, you acknowledge that you have read and understood our Health & Safety Guidelines. </p>

 

<h6>7. Children </h6>

 

<p>Use of<a href="http://www.jagtu.com/home.html" target="_blank" rel="noopener noreferrer"> www.jagtu.com</a> is available only to persons who can form a legally binding contract under the Indian Contract Act, 1872. If you are a minor i.e. under the age of 18 years, you may purchase only with the involvement of a parent or guardian.</p> 

 

<h6>8. Communications </h6>

 

<p>When you visit www.jagtu.com, you are communicating with us electronically. You will be required to provide a valid phone number while placing an order with us. We may communicate with you by e-mail, SMS, phone call or by posting notices on the website or by any other mode of communication. For contractual purposes, you consent to receive communications including SMS, e-mails or phone calls from us with respect to your order.</p> 

 

<h6>9. Losses </h6>

 

<p>We will not be responsible for any business loss (including loss of profits, revenue, contracts, anticipated savings, data, goodwill or wasted expenditure) or any other indirect or consequential loss that is not reasonably foreseeable to both you and us when a contract for the sale of goods by us to you was formed. </p>

<h6>10. Alteration or Amendments to the Conditions</h6> 

 

<p>We reserve the right to make changes to our policies, and these Conditions of Sale at any time. You will be subject to the policies and Conditions of Sale in force at the time you order goods from us, unless any change to those policies or these conditions is required to be made by law or government authority (in which case it will apply to orders previously placed by you). If any of these conditions is deemed invalid, void, or for any reason unenforceable, that condition will be deemed severable and will not affect the validity and enforceability of any remaining condition. </p>

 

<h6>11. Events beyond our reasonable control </h6>

 

<p>We will not be held responsible for any delay or failure to comply with our obligations under these conditions if the delay or failure arises from any cause which is beyond our reasonable control. This condition does not affect your statutory rights. </p>

 

<h6>12. Waiver</h6> 

 

<p>If you breach these conditions and we take no action, we will still be entitled to use our rights and remedies in any other situation where you breach these conditions. </p>

<h6>13. Governing Law and Jurisdiction </h6>

 

<p>These conditions are governed by and construed in accordance with the laws of India, and the application of the United Nations Convention on Contracts for the International Sale of Goods is expressly excluded. You agree, as we do, to submit to the exclusive jurisdiction of the courts at Lucknow. </p>

 







</div>
</div>

      </div>
    )
  }
}
export default termsandconditions;
